/* tslint:disable */
/* eslint-disable */
/**
 * App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Coordinates
 */
export interface Coordinates {
    /**
     * 
     * @type {string}
     * @memberof Coordinates
     */
    'type'?: CoordinatesTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof Coordinates
     */
    'coordinates': Array<number>;
}

export const CoordinatesTypeEnum = {
    Point: 'Point'
} as const;

export type CoordinatesTypeEnum = typeof CoordinatesTypeEnum[keyof typeof CoordinatesTypeEnum];

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface Journey
 */
export interface Journey {
    /**
     * 
     * @type {string}
     * @memberof Journey
     */
    '_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Journey
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Journey
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Journey
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof Journey
     */
    'created_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Journey
     */
    'active': boolean;
}
/**
 * 
 * @export
 * @interface Marker
 */
export interface Marker {
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    '_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    'journey_id': string;
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    'marker_type': MarkerMarkerTypeEnum;
    /**
     * 
     * @type {Coordinates}
     * @memberof Marker
     */
    'coordinates': Coordinates;
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    'timestamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    'estimated_time'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof Marker
     */
    'created_at'?: string;
}

export const MarkerMarkerTypeEnum = {
    Past: 'past',
    Plan: 'plan'
} as const;

export type MarkerMarkerTypeEnum = typeof MarkerMarkerTypeEnum[keyof typeof MarkerMarkerTypeEnum];

/**
 * 
 * @export
 * @interface Tokens
 */
export interface Tokens {
    /**
     * 
     * @type {string}
     * @memberof Tokens
     */
    'access_token': string;
    /**
     * 
     * @type {string}
     * @memberof Tokens
     */
    'refresh_token': string;
    /**
     * 
     * @type {string}
     * @memberof Tokens
     */
    'token_type'?: string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    '_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phonenumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'country'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_verified'?: boolean;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Authenticate a user via their password and return an access token adn refresh token.
         * @summary Login
         * @param {string} username 
         * @param {string} password 
         * @param {string | null} [grantType] 
         * @param {string} [scope] 
         * @param {string | null} [clientId] 
         * @param {string | null} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiV1AuthTokenPost: async (username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('loginApiV1AuthTokenPost', 'username', username)
            // verify required parameter 'password' is not null or undefined
            assertParamExists('loginApiV1AuthTokenPost', 'password', password)
            const localVarPath = `/api/v1/auth/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (grantType !== undefined) { 
                localVarFormParams.set('grant_type', grantType as any);
            }
    
            if (username !== undefined) { 
                localVarFormParams.set('username', username as any);
            }
    
            if (password !== undefined) { 
                localVarFormParams.set('password', password as any);
            }
    
            if (scope !== undefined) { 
                localVarFormParams.set('scope', scope as any);
            }
    
            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }
    
            if (clientSecret !== undefined) { 
                localVarFormParams.set('client_secret', clientSecret as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh
         * @param {string} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshApiV1AuthRefreshPost: async (refreshToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refreshToken' is not null or undefined
            assertParamExists('refreshApiV1AuthRefreshPost', 'refreshToken', refreshToken)
            const localVarPath = `/api/v1/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (refreshToken !== undefined) {
                localVarQueryParameter['refresh_token'] = refreshToken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Authenticate a user via their password and return an access token adn refresh token.
         * @summary Login
         * @param {string} username 
         * @param {string} password 
         * @param {string | null} [grantType] 
         * @param {string} [scope] 
         * @param {string | null} [clientId] 
         * @param {string | null} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginApiV1AuthTokenPost(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Tokens>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginApiV1AuthTokenPost(username, password, grantType, scope, clientId, clientSecret, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.loginApiV1AuthTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh
         * @param {string} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshApiV1AuthRefreshPost(refreshToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshApiV1AuthRefreshPost(refreshToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.refreshApiV1AuthRefreshPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Authenticate a user via their password and return an access token adn refresh token.
         * @summary Login
         * @param {string} username 
         * @param {string} password 
         * @param {string | null} [grantType] 
         * @param {string} [scope] 
         * @param {string | null} [clientId] 
         * @param {string | null} [clientSecret] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginApiV1AuthTokenPost(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<Tokens> {
            return localVarFp.loginApiV1AuthTokenPost(username, password, grantType, scope, clientId, clientSecret, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh
         * @param {string} refreshToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshApiV1AuthRefreshPost(refreshToken: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.refreshApiV1AuthRefreshPost(refreshToken, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * Authenticate a user via their password and return an access token adn refresh token.
     * @summary Login
     * @param {string} username 
     * @param {string} password 
     * @param {string | null} [grantType] 
     * @param {string} [scope] 
     * @param {string | null} [clientId] 
     * @param {string | null} [clientSecret] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public loginApiV1AuthTokenPost(username: string, password: string, grantType?: string | null, scope?: string, clientId?: string | null, clientSecret?: string | null, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).loginApiV1AuthTokenPost(username, password, grantType, scope, clientId, clientSecret, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh
     * @param {string} refreshToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public refreshApiV1AuthRefreshPost(refreshToken: string, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).refreshApiV1AuthRefreshPost(refreshToken, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve users.
         * @summary Ping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingApiV1Get: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve users.
         * @summary Ping Mongodb
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingMongodbApiV1MongodbGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/mongodb`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve users.
         * @summary Ping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingApiV1Get(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingApiV1Get(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pingApiV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve users.
         * @summary Ping Mongodb
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingMongodbApiV1MongodbGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingMongodbApiV1MongodbGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pingMongodbApiV1MongodbGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Retrieve users.
         * @summary Ping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingApiV1Get(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.pingApiV1Get(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve users.
         * @summary Ping Mongodb
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingMongodbApiV1MongodbGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.pingMongodbApiV1MongodbGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Retrieve users.
     * @summary Ping
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public pingApiV1Get(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pingApiV1Get(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve users.
     * @summary Ping Mongodb
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public pingMongodbApiV1MongodbGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pingMongodbApiV1MongodbGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * JourneysApi - axios parameter creator
 * @export
 */
export const JourneysApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a marker to a journey.
         * @summary Add Marker To Journey
         * @param {string} journeyId 
         * @param {Marker} marker 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost: async (journeyId: string, marker: Marker, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyId' is not null or undefined
            assertParamExists('addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost', 'journeyId', journeyId)
            // verify required parameter 'marker' is not null or undefined
            assertParamExists('addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost', 'marker', marker)
            const localVarPath = `/api/v1/journeys/{journey_id}/markers`
                .replace(`{${"journey_id"}}`, encodeURIComponent(String(journeyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(marker, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Register a new journey.
         * @summary Create Journey
         * @param {Journey} journey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyApiV1JourneysPost: async (journey: Journey, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journey' is not null or undefined
            assertParamExists('createJourneyApiV1JourneysPost', 'journey', journey)
            const localVarPath = `/api/v1/journeys/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(journey, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJourneyApiV1JourneysJourneyIdDelete: async (journeyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyId' is not null or undefined
            assertParamExists('deleteJourneyApiV1JourneysJourneyIdDelete', 'journeyId', journeyId)
            const localVarPath = `/api/v1/journeys/{journey_id}`
                .replace(`{${"journey_id"}}`, encodeURIComponent(String(journeyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a journey by ID.
         * @summary Get Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyApiV1JourneysJourneyIdGet: async (journeyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyId' is not null or undefined
            assertParamExists('getJourneyApiV1JourneysJourneyIdGet', 'journeyId', journeyId)
            const localVarPath = `/api/v1/journeys/{journey_id}`
                .replace(`{${"journey_id"}}`, encodeURIComponent(String(journeyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all markers for a journey.
         * @summary Get Journey Markers
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyMarkersApiV1JourneysJourneyIdMarkersGet: async (journeyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyId' is not null or undefined
            assertParamExists('getJourneyMarkersApiV1JourneysJourneyIdMarkersGet', 'journeyId', journeyId)
            const localVarPath = `/api/v1/journeys/{journey_id}/markers`
                .replace(`{${"journey_id"}}`, encodeURIComponent(String(journeyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all journeys with markers near the markers of a given journey.
         * @summary Get Nearby Journeys
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet: async (journeyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyId' is not null or undefined
            assertParamExists('getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet', 'journeyId', journeyId)
            const localVarPath = `/api/v1/journeys/{journey_id}/journeys/nearby`
                .replace(`{${"journey_id"}}`, encodeURIComponent(String(journeyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Toggle Active Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleActiveJourneyApiV1JourneysJourneyIdActivePatch: async (journeyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'journeyId' is not null or undefined
            assertParamExists('toggleActiveJourneyApiV1JourneysJourneyIdActivePatch', 'journeyId', journeyId)
            const localVarPath = `/api/v1/journeys/{journey_id}/active`
                .replace(`{${"journey_id"}}`, encodeURIComponent(String(journeyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JourneysApi - functional programming interface
 * @export
 */
export const JourneysApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JourneysApiAxiosParamCreator(configuration)
    return {
        /**
         * Add a marker to a journey.
         * @summary Add Marker To Journey
         * @param {string} journeyId 
         * @param {Marker} marker 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost(journeyId: string, marker: Marker, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Marker>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost(journeyId, marker, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Register a new journey.
         * @summary Create Journey
         * @param {Journey} journey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createJourneyApiV1JourneysPost(journey: Journey, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Journey>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createJourneyApiV1JourneysPost(journey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.createJourneyApiV1JourneysPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteJourneyApiV1JourneysJourneyIdDelete(journeyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteJourneyApiV1JourneysJourneyIdDelete(journeyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.deleteJourneyApiV1JourneysJourneyIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a journey by ID.
         * @summary Get Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyApiV1JourneysJourneyIdGet(journeyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Journey>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyApiV1JourneysJourneyIdGet(journeyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.getJourneyApiV1JourneysJourneyIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all markers for a journey.
         * @summary Get Journey Markers
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJourneyMarkersApiV1JourneysJourneyIdMarkersGet(journeyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Marker>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJourneyMarkersApiV1JourneysJourneyIdMarkersGet(journeyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.getJourneyMarkersApiV1JourneysJourneyIdMarkersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all journeys with markers near the markers of a given journey.
         * @summary Get Nearby Journeys
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet(journeyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet(journeyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Toggle Active Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async toggleActiveJourneyApiV1JourneysJourneyIdActivePatch(journeyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toggleActiveJourneyApiV1JourneysJourneyIdActivePatch(journeyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JourneysApi.toggleActiveJourneyApiV1JourneysJourneyIdActivePatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JourneysApi - factory interface
 * @export
 */
export const JourneysApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JourneysApiFp(configuration)
    return {
        /**
         * Add a marker to a journey.
         * @summary Add Marker To Journey
         * @param {string} journeyId 
         * @param {Marker} marker 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost(journeyId: string, marker: Marker, options?: RawAxiosRequestConfig): AxiosPromise<Marker> {
            return localVarFp.addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost(journeyId, marker, options).then((request) => request(axios, basePath));
        },
        /**
         * Register a new journey.
         * @summary Create Journey
         * @param {Journey} journey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createJourneyApiV1JourneysPost(journey: Journey, options?: RawAxiosRequestConfig): AxiosPromise<Journey> {
            return localVarFp.createJourneyApiV1JourneysPost(journey, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteJourneyApiV1JourneysJourneyIdDelete(journeyId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.deleteJourneyApiV1JourneysJourneyIdDelete(journeyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a journey by ID.
         * @summary Get Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyApiV1JourneysJourneyIdGet(journeyId: string, options?: RawAxiosRequestConfig): AxiosPromise<Journey> {
            return localVarFp.getJourneyApiV1JourneysJourneyIdGet(journeyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all markers for a journey.
         * @summary Get Journey Markers
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJourneyMarkersApiV1JourneysJourneyIdMarkersGet(journeyId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Marker>> {
            return localVarFp.getJourneyMarkersApiV1JourneysJourneyIdMarkersGet(journeyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all journeys with markers near the markers of a given journey.
         * @summary Get Nearby Journeys
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet(journeyId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet(journeyId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Toggle Active Journey
         * @param {string} journeyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleActiveJourneyApiV1JourneysJourneyIdActivePatch(journeyId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.toggleActiveJourneyApiV1JourneysJourneyIdActivePatch(journeyId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JourneysApi - object-oriented interface
 * @export
 * @class JourneysApi
 * @extends {BaseAPI}
 */
export class JourneysApi extends BaseAPI {
    /**
     * Add a marker to a journey.
     * @summary Add Marker To Journey
     * @param {string} journeyId 
     * @param {Marker} marker 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost(journeyId: string, marker: Marker, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).addMarkerToJourneyApiV1JourneysJourneyIdMarkersPost(journeyId, marker, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register a new journey.
     * @summary Create Journey
     * @param {Journey} journey 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public createJourneyApiV1JourneysPost(journey: Journey, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).createJourneyApiV1JourneysPost(journey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Journey
     * @param {string} journeyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public deleteJourneyApiV1JourneysJourneyIdDelete(journeyId: string, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).deleteJourneyApiV1JourneysJourneyIdDelete(journeyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a journey by ID.
     * @summary Get Journey
     * @param {string} journeyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public getJourneyApiV1JourneysJourneyIdGet(journeyId: string, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).getJourneyApiV1JourneysJourneyIdGet(journeyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all markers for a journey.
     * @summary Get Journey Markers
     * @param {string} journeyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public getJourneyMarkersApiV1JourneysJourneyIdMarkersGet(journeyId: string, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).getJourneyMarkersApiV1JourneysJourneyIdMarkersGet(journeyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all journeys with markers near the markers of a given journey.
     * @summary Get Nearby Journeys
     * @param {string} journeyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet(journeyId: string, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).getNearbyJourneysApiV1JourneysJourneyIdJourneysNearbyGet(journeyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Toggle Active Journey
     * @param {string} journeyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JourneysApi
     */
    public toggleActiveJourneyApiV1JourneysJourneyIdActivePatch(journeyId: string, options?: RawAxiosRequestConfig) {
        return JourneysApiFp(this.configuration).toggleActiveJourneyApiV1JourneysJourneyIdActivePatch(journeyId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the current authenticated user.
         * @summary Get Current User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUserApiV1UsersMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a user by ID.
         * @summary Get User By Id
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByIdApiV1UsersUserIdGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserByIdApiV1UsersUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get journeys for a specific user.
         * @summary Get User Journeys
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserJourneysApiV1UsersUserIdJourneysGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserJourneysApiV1UsersUserIdJourneysGet', 'userId', userId)
            const localVarPath = `/api/v1/users/{user_id}/journeys`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Register a new user.
         * @summary Register User
         * @param {User} user 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUserApiV1UsersRegisterPost: async (user: User, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'user' is not null or undefined
            assertParamExists('registerUserApiV1UsersRegisterPost', 'user', user)
            const localVarPath = `/api/v1/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(user, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reset Password
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPasswordApiV1UsersResetPasswordPost: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('resetPasswordApiV1UsersResetPasswordPost', 'email', email)
            const localVarPath = `/api/v1/users/reset-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Password
         * @param {string} token 
         * @param {string} newPassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePasswordApiV1UsersUpdatePasswordPost: async (token: string, newPassword: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('updatePasswordApiV1UsersUpdatePasswordPost', 'token', token)
            // verify required parameter 'newPassword' is not null or undefined
            assertParamExists('updatePasswordApiV1UsersUpdatePasswordPost', 'newPassword', newPassword)
            const localVarPath = `/api/v1/users/update-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            if (newPassword !== undefined) {
                localVarQueryParameter['new_password'] = newPassword;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify Email
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmailApiV1UsersVerifyEmailGet: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('verifyEmailApiV1UsersVerifyEmailGet', 'token', token)
            const localVarPath = `/api/v1/users/verify-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Get the current authenticated user.
         * @summary Get Current User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUserApiV1UsersMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUserApiV1UsersMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getCurrentUserApiV1UsersMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a user by ID.
         * @summary Get User By Id
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserByIdApiV1UsersUserIdGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserByIdApiV1UsersUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserByIdApiV1UsersUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get journeys for a specific user.
         * @summary Get User Journeys
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserJourneysApiV1UsersUserIdJourneysGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserJourneysApiV1UsersUserIdJourneysGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserJourneysApiV1UsersUserIdJourneysGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Register a new user.
         * @summary Register User
         * @param {User} user 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUserApiV1UsersRegisterPost(user: User, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUserApiV1UsersRegisterPost(user, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.registerUserApiV1UsersRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reset Password
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetPasswordApiV1UsersResetPasswordPost(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetPasswordApiV1UsersResetPasswordPost(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.resetPasswordApiV1UsersResetPasswordPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Password
         * @param {string} token 
         * @param {string} newPassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePasswordApiV1UsersUpdatePasswordPost(token: string, newPassword: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePasswordApiV1UsersUpdatePasswordPost(token, newPassword, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updatePasswordApiV1UsersUpdatePasswordPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Verify Email
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyEmailApiV1UsersVerifyEmailGet(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEmailApiV1UsersVerifyEmailGet(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.verifyEmailApiV1UsersVerifyEmailGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * Get the current authenticated user.
         * @summary Get Current User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUserApiV1UsersMeGet(options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.getCurrentUserApiV1UsersMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get a user by ID.
         * @summary Get User By Id
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByIdApiV1UsersUserIdGet(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.getUserByIdApiV1UsersUserIdGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get journeys for a specific user.
         * @summary Get User Journeys
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserJourneysApiV1UsersUserIdJourneysGet(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getUserJourneysApiV1UsersUserIdJourneysGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Register a new user.
         * @summary Register User
         * @param {User} user 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUserApiV1UsersRegisterPost(user: User, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.registerUserApiV1UsersRegisterPost(user, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reset Password
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPasswordApiV1UsersResetPasswordPost(email: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.resetPasswordApiV1UsersResetPasswordPost(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Password
         * @param {string} token 
         * @param {string} newPassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePasswordApiV1UsersUpdatePasswordPost(token: string, newPassword: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.updatePasswordApiV1UsersUpdatePasswordPost(token, newPassword, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify Email
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmailApiV1UsersVerifyEmailGet(token: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.verifyEmailApiV1UsersVerifyEmailGet(token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * Get the current authenticated user.
     * @summary Get Current User
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getCurrentUserApiV1UsersMeGet(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getCurrentUserApiV1UsersMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a user by ID.
     * @summary Get User By Id
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserByIdApiV1UsersUserIdGet(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserByIdApiV1UsersUserIdGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get journeys for a specific user.
     * @summary Get User Journeys
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserJourneysApiV1UsersUserIdJourneysGet(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserJourneysApiV1UsersUserIdJourneysGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register a new user.
     * @summary Register User
     * @param {User} user 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public registerUserApiV1UsersRegisterPost(user: User, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).registerUserApiV1UsersRegisterPost(user, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reset Password
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public resetPasswordApiV1UsersResetPasswordPost(email: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).resetPasswordApiV1UsersResetPasswordPost(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Password
     * @param {string} token 
     * @param {string} newPassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public updatePasswordApiV1UsersUpdatePasswordPost(token: string, newPassword: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updatePasswordApiV1UsersUpdatePasswordPost(token, newPassword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify Email
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public verifyEmailApiV1UsersVerifyEmailGet(token: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).verifyEmailApiV1UsersVerifyEmailGet(token, options).then((request) => request(this.axios, this.basePath));
    }
}



